const STORE='ws_inventory_v1';
const U=['PCS','PKT','DOZEN','CASE','CTN','KG','G','L','ML'];
const $=id=>document.getElementById(id), money=n=>'MVR '+Number(n||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function read(){try{return JSON.parse(localStorage.getItem(STORE))||{invoices:[],stock:{},prices:{}}}catch{return{invoices:[],stock:{},prices:{}}}}
function write(d){localStorage.setItem(STORE,JSON.stringify(d))}
function csvDownload(name,headers,rows){const q=v=>'"'+String(v??'').replace(/"/g,'""')+'"',blob=new Blob([[headers,...rows].map(r=>r.map(q).join(',')).join('\n')],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
async function catalogue(){try{const t=await fetch('data.csv').then(r=>r.text()),lines=t.replace(/^\uFEFF/,'').split(/\r?\n/).slice(1);return lines.map(x=>{const p=x.split(',');return{vendor:p[0]?.trim(),name:p.slice(1,-2).join(',').trim(),unit:p.at(-2)?.trim(),rate:+p.at(-1)||0}}).filter(x=>x.name)}catch{return[]}}
function supplyPage(){let cat=[];const body=$('lines'),tpl=$('rowTemplate');$('invoiceDate').value=new Date().toISOString().slice(0,10);
 function add(seed={}){const tr=tpl.content.firstElementChild.cloneNode(true);body.append(tr);tr.querySelector('.item').value=seed.name||'';tr.querySelector('.purchaseUnit').value=U.includes(seed.unit)?seed.unit:'PCS';tr.querySelector('.rate').value=seed.rate||'';tr.querySelectorAll('input,select').forEach(x=>x.addEventListener('input',calc));tr.querySelector('.item').addEventListener('change',()=>{const c=cat.find(x=>x.name===tr.querySelector('.item').value);if(c){tr.querySelector('.purchaseUnit').value=U.includes(c.unit)?c.unit:'PCS';tr.querySelector('.rate').value=c.rate;calc()}});tr.querySelector('.remove').onclick=()=>{tr.remove();if(!body.children.length)add();calc()};calc()}
 function rows(){return[...body.querySelectorAll('.line')].map(tr=>{const name=tr.querySelector('.item').value.trim(),purchaseUnit=tr.querySelector('.purchaseUnit').value,qty=+tr.querySelector('.qty').value||0,packSize=+tr.querySelector('.pack').value||0,baseUnit=tr.querySelector('.baseUnit').value,rate=+tr.querySelector('.rate').value||0;return{name,purchaseUnit,qty,packSize,baseUnit,rate,total:qty*rate,baseQty:qty*packSize}})}
 function calc(){let valid=0,total=0;[...body.children].forEach((tr,i)=>{const r=rows()[i];tr.querySelector('.lineTotal').textContent=money(r.total).replace('MVR ','');if(r.name&&r.qty>0&&r.rate>0){valid++;total+=r.total}});$('grandTotal').textContent=money(total);$('lineCount').textContent=valid+' valid item'+(valid===1?'':'s')}
 function history(){const d=read();$('history').innerHTML=d.invoices.map(inv=>`<article class="invoice-card"><div><h3>${esc(inv.vendor)}</h3><p>${esc(inv.invoiceNo)} · ${esc(inv.date)} · ${inv.lines.length} items</p></div><div class="amount">${money(inv.total)}</div><div class="invoice-lines">${inv.lines.map(x=>esc(x.name)+' — '+x.qty+' '+x.purchaseUnit+' = '+money(x.total)).join('<br>')}</div></article>`).join('')||'<div class="empty">No supply invoices saved yet.</div>'}
 $('addRow').onclick=()=>add();$('loadExample').onclick=()=>{$('vendor').value='HAPPY MARKET';$('invoiceNo').value='DEMO-'+Date.now().toString().slice(-5);body.innerHTML='';add({name:'PASTA SPAGHETTI (20X500 GM)',unit:'CASE',rate:490});const tr=body.children[0];tr.querySelector('.pack').value=10000;tr.querySelector('.baseUnit').value='g';calc()};
 $('saveInvoice').onclick=()=>{const vendor=$('vendor').value.trim(),invoiceNo=$('invoiceNo').value.trim(),date=$('invoiceDate').value,valid=rows().filter(x=>x.name&&x.qty>0&&x.rate>0&&x.packSize>0);if(!vendor||!invoiceNo||!date||!valid.length){$('message').className='error';$('message').textContent='Supplier, invoice number, date and at least one complete item are required.';return}const d=read();if(d.invoices.some(x=>x.invoiceNo.toLowerCase()===invoiceNo.toLowerCase())){$('message').className='error';$('message').textContent='This invoice number already exists.';return}const inv={id:crypto.randomUUID?.()||String(Date.now()),vendor,invoiceNo,date,notes:$('notes').value.trim(),createdAt:new Date().toISOString(),lines:valid,total:valid.reduce((s,x)=>s+x.total,0)};d.invoices.unshift(inv);valid.forEach(x=>{const k=x.name.toLowerCase();d.stock[k]=d.stock[k]||{name:x.name,unit:x.baseUnit,qty:0};d.stock[k].qty+=x.baseQty;d.stock[k].unit=x.baseUnit;d.prices[k]=d.prices[k]||[];d.prices[k].unshift({vendor,invoiceNo,date,rate:x.rate,purchaseUnit:x.purchaseUnit,packSize:x.packSize,baseUnit:x.baseUnit,baseRate:x.rate/x.packSize})});write(d);$('message').className='ok';$('message').textContent='Saved. Bill total, stock and price history updated.';$('invoiceNo').value='';$('notes').value='';body.innerHTML='';add();calc();history()};$('clearDemo').onclick=()=>{if(confirm('Clear all locally saved supply, bill, stock and price data?')){localStorage.removeItem(STORE);history()}};
 catalogue().then(c=>{cat=c;$('items').innerHTML=c.map(x=>`<option value="${esc(x.name)}"></option>`).join('');$('vendors').innerHTML=[...new Set(c.map(x=>x.vendor).filter(Boolean))].sort().map(x=>`<option value="${esc(x)}"></option>`).join('')});add();add();history()}
function billsPage(){const render=()=>{const d=read(),q=$('billSearch').value.toLowerCase(),from=$('billFrom').value,to=$('billTo').value,rows=d.invoices.filter(x=>(!q||(x.vendor+' '+x.invoiceNo).toLowerCase().includes(q))&&(!from||x.date>=from)&&(!to||x.date<=to));$('billGrand').textContent=money(rows.reduce((s,x)=>s+x.total,0));$('billCount').textContent=rows.length+' invoice'+(rows.length===1?'':'s');$('billList').innerHTML=rows.map(x=>`<article class="invoice-card"><div><h3>${esc(x.vendor)}</h3><p>${esc(x.invoiceNo)} · ${esc(x.date)} · ${x.lines.length} items</p></div><div class="amount">${money(x.total)}</div><div class="invoice-lines">${x.lines.map(i=>esc(i.name)+' — '+i.qty+' '+i.purchaseUnit).join('<br>')}</div></article>`).join('')||'<div class="empty">No matching bills.</div>'};['billSearch','billFrom','billTo'].forEach(id=>$(id).addEventListener('input',render));$('exportBills').onclick=()=>{const d=read();csvDownload('supply-bills.csv',['Invoice ID','Date','Supplier','Invoice No','Items','Total MVR'],d.invoices.map(x=>[x.id,x.date,x.vendor,x.invoiceNo,x.lines.length,x.total.toFixed(2)]))};render()}
function pricesPage(){const render=()=>{const d=read(),q=$('priceSearch').value.toLowerCase();let rows=Object.values(d.prices).map(h=>{const a=h[0],b=h[1],change=b?((a.rate-b.rate)/b.rate*100):0;return{...a,name:Object.keys(d.prices).find(k=>d.prices[k]===h),change,previous:b?.rate}}).filter(x=>(x.name+' '+x.vendor).toLowerCase().includes(q));const sort=$('priceSort').value;rows.sort((a,b)=>sort==='high'?b.rate-a.rate:sort==='change'?Math.abs(b.change)-Math.abs(a.change):a.name.localeCompare(b.name));$('priceCount').textContent=rows.length;$('priceGrid').innerHTML=rows.map(x=>`<article class="price-card"><h3>${esc(d.stock[x.name]?.name||x.name)}</h3><p>${esc(x.vendor)} · ${esc(x.purchaseUnit)} · ${esc(x.date)}</p><div class="rate">${money(x.rate)}</div><div class="change ${x.change>0?'up':x.change<0?'down':'flat'}">${x.previous==null?'First saved rate':(x.change>0?'▲ +':'▼ ')+Math.abs(x.change).toFixed(1)+'% from '+money(x.previous)}</div><p>Kitchen rate: ${money(x.baseRate)} / ${esc(x.baseUnit)}</p></article>`).join('')||'<div class="empty">No matching price records.</div>'};$('priceSearch').oninput=render;$('priceSort').onchange=render;$('exportPrices').onclick=()=>{const d=read(),rows=Object.entries(d.prices).map(([k,h])=>[d.stock[k]?.name||k,h[0].vendor,h[0].date,h[0].purchaseUnit,h[0].rate,h[0].baseUnit,h[0].baseRate]);csvDownload('latest-prices.csv',['Item','Supplier','Date','Purchase Unit','Purchase Rate','Kitchen Unit','Kitchen Rate'],rows)};render()}
const page=document.body.dataset.page;if(page==='supply')supplyPage();if(page==='bills')billsPage();if(page==='prices')pricesPage();
