const money=n=>`MVR ${Number(n||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
export function renderAccounts(bundle){
 const accounts=bundle.accounts||[],transfers=bundle.accountTransfers||[],month=bundle.month||{};
 const payments=(bundle.payments||[]).filter(p=>!p.reversed_at),receivableTx=(bundle.receivableTransactions||[]).filter(t=>!t.reversed_at);
 const balances=new Map(accounts.map(a=>[a.id,Number(a.opening_balance||0)]));
 if(month.income_account_id&&balances.has(month.income_account_id)) balances.set(month.income_account_id,balances.get(month.income_account_id)+Number(month.income||0));
 for(const p of payments) if(p.account_id&&balances.has(p.account_id)) balances.set(p.account_id,balances.get(p.account_id)-Number(p.amount||0));
 for(const t of receivableTx) if(t.account_id&&balances.has(t.account_id)){const sign=t.transaction_type==='repayment'?1:-1;balances.set(t.account_id,balances.get(t.account_id)+sign*Number(t.amount||0));}
 for(const t of transfers.filter(x=>!x.reversed_at)){if(balances.has(t.from_account_id))balances.set(t.from_account_id,balances.get(t.from_account_id)-Number(t.amount||0));if(balances.has(t.to_account_id))balances.set(t.to_account_id,balances.get(t.to_account_id)+Number(t.amount||0));}
 const available=accounts.length?[...balances.values()].reduce((s,v)=>s+v,0):Number(month.bank_balance||0),map=new Map(accounts.map(a=>[a.id,a]));
 return `<section class="page-head"><div><p class="eyebrow">WHERE YOUR MONEY LIVES</p><h1>Accounts</h1><p>Bank and cash balances update from the account selected for each new money movement.</p></div><div class="page-head-actions"><button class="button secondary" data-action="transfer-account">Transfer</button><button class="button primary" data-action="add-account">+ Add account</button></div></section>
 <section class="account-hero"><div><span>COMBINED AVAILABLE</span><strong>${money(available)}</strong><small>Across all tracked accounts</small></div><div><span>ACCOUNTS</span><strong>${accounts.length}</strong><small>Active money locations</small></div></section>
 <section class="account-list">${accounts.map(a=>`<article class="money-account"><div class="account-symbol">${a.account_type==='cash'?'◫':'▤'}</div><div><b>${a.name}</b><small>${a.account_type==='cash'?'Cash':'Bank account'}${a.is_primary?' · Primary':''}</small></div><div><small>Live balance</small><strong>${money(balances.get(a.id))}</strong></div></article>`).join('')}</section>
 ${transfers.length?`<section class="account-transfer-list"><div class="insight-title"><h2>Transfers this month</h2><span>${transfers.length} transfer${transfers.length===1?'':'s'}</span></div>${transfers.map(t=>`<div class="account-transfer-row"><div><b>${map.get(t.from_account_id)?.name||'Account'} → ${map.get(t.to_account_id)?.name||'Account'}</b><small>${t.transfer_date}${t.note?' · '+t.note:''}</small></div><strong>${money(t.amount)}</strong></div>`).join('')}</section>`:''}`;
}