const $=s=>document.querySelector(s);const canvas=$('#publisherCanvas');const ctx=canvas.getContext('2d');const state={width:1080,height:1350,image:null,imageX:0,imageY:0,scale:1,minScale:.2,maxScale:8,drag:false,lastX:0,lastY:0,quote:'މިއީ ނައްޕެ ޕަބްލިޝަރ ސްޓޫޑިއޯގެ ކުއިކް މޯޑެވެ.',speaker:'ނޭޝަން ޗެޓް',source:'NAAPPE',overlayStart:.43,overlayOpacity:.96,overlayBlur:10,accent:'#168f87'};canvas.width=state.width;canvas.height=state.height;
function fitImage(){if(!state.image)return;const s=Math.max(state.width/state.image.width,state.height/state.image.height);state.scale=s;state.imageX=(state.width-state.image.width*s)/2;state.imageY=(state.height-state.image.height*s)/2;render()}
function resetImage(){fitImage()}
function pointerPosition(event){const r=canvas.getBoundingClientRect();return{x:(event.clientX-r.left)*state.width/r.width,y:(event.clientY-r.top)*state.height/r.height}}
function zoomAt(x,y,next){if(!state.image)return;next=Math.min(state.maxScale,Math.max(state.minScale,next));const localX=(x-state.imageX)/state.scale;const localY=(y-state.imageY)/state.scale;state.scale=next;state.imageX=x-localX*next;state.imageY=y-localY*next;render()}
canvas.addEventListener('pointerdown',e=>{if(!state.image)return;canvas.setPointerCapture(e.pointerId);const p=pointerPosition(e);state.drag=true;state.lastX=p.x;state.lastY=p.y});canvas.addEventListener('pointermove',e=>{if(!state.drag)return;const p=pointerPosition(e);state.imageX+=p.x-state.lastX;state.imageY+=p.y-state.lastY;state.lastX=p.x;state.lastY=p.y;render()});canvas.addEventListener('pointerup',()=>state.drag=false);canvas.addEventListener('pointercancel',()=>state.drag=false);canvas.addEventListener('wheel',e=>{e.preventDefault();const p=pointerPosition(e);zoomAt(p.x,p.y,state.scale*Math.exp(-e.deltaY*.001))},{passive:false});canvas.addEventListener('dblclick',fitImage);
function wrapText(text,maxWidth,font){ctx.font=font;const words=[...text];const lines=[];let line='';for(const char of words){const test=line+char;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=char}else line=test}if(line)lines.push(line);return lines}
function drawImage(){ctx.fillStyle='#dfe6ec';ctx.fillRect(0,0,state.width,state.height);if(!state.image)return;ctx.save();ctx.filter='brightness(1) contrast(1)';ctx.drawImage(state.image,state.imageX,state.imageY,state.image.width*state.scale,state.image.height*state.scale);ctx.restore()}
function drawOverlay(){const start=state.height*state.overlayStart;const g=ctx.createLinearGradient(0,start,0,state.height*.82);g.addColorStop(0,'rgba(255,255,255,0)');g.addColorStop(.36,`rgba(255,255,255,${state.overlayOpacity*.72})`);g.addColorStop(1,`rgba(255,255,255,${state.overlayOpacity})`);ctx.fillStyle=g;ctx.fillRect(0,start,state.width,state.height-start)}
function drawText(){ctx.textAlign='center';ctx.direction='rtl';ctx.fillStyle=state.accent;ctx.font='600 38px Arial';ctx.fillText(state.speaker,state.width/2,state.height*.62);ctx.font='700 73px "Noto Sans Thaana",Arial';const lines=wrapText(state.quote,state.width*.78,ctx.font).slice(0,6);const lineHeight=100;const startY=state.height*.69;lines.forEach((line,i)=>ctx.fillText(line,state.width/2,startY+i*lineHeight));ctx.direction='ltr';ctx.font='700 28px Arial';ctx.fillStyle='#1c2737';ctx.fillText(state.source,100,state.height-55);ctx.font='800 42px Arial';ctx.fillStyle=state.accent;ctx.fillText('naappe',state.width-112,state.height-55)}
function render(){ctx.clearRect(0,0,state.width,state.height);drawImage();drawOverlay();drawText();$('#zoomValue').textContent=Math.round(state.scale*100)+'%'}
$('#imageUpload').addEventListener('change',e=>{const file=e.target.files?.[0];if(!file)return;const image=new Image();image.onload=()=>{state.image=image;fitImage();URL.revokeObjectURL(image.src)};image.src=URL.createObjectURL(file)});$('#quote').addEventListener('input',e=>{state.quote=e.target.value;render()});$('#speaker').addEventListener('input',e=>{state.speaker=e.target.value;render()});$('#source').addEventListener('input',e=>{state.source=e.target.value;render()});$('#overlayStart').addEventListener('input',e=>{state.overlayStart=Number(e.target.value);$('#overlayStartValue').value=Math.round(state.overlayStart*100)+'%';render()});$('#overlayOpacity').addEventListener('input',e=>{state.overlayOpacity=Number(e.target.value);$('#overlayOpacityValue').value=Math.round(state.overlayOpacity*100)+'%';render()});$('#accent').addEventListener('input',e=>{state.accent=e.target.value;render()});$('#fitImage').onclick=fitImage;$('#resetImage').onclick=resetImage;$('#exportPng').onclick=()=>{render();const a=document.createElement('a');a.download='naappe-nationchat-1080x1350.png';a.href=canvas.toDataURL('image/png');a.click()};document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-mode]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.body.classList.toggle('studio-mode',b.dataset.mode==='studio')});render();