const $=s=>document.querySelector(s);const canvas=$('#publisherCanvas'),ctx=canvas.getContext('2d');canvas.width=1080;canvas.height=1350;
const state={elements:[],selectedId:null,history:[],future:[],background:'#ffffff'};let interaction=null;
function uid(){return crypto.randomUUID()}function clone(v){return JSON.parse(JSON.stringify(v))}function selected(){return state.elements.find(e=>e.id===state.selectedId)||null}
function snapshot(){state.history.push(JSON.stringify(state.elements));if(state.history.length>80)state.history.shift();state.future=[]}function restore(serialized){state.elements=JSON.parse(serialized);state.selectedId=null;renderAll()}
function undo(){if(!state.history.length)return;state.future.push(JSON.stringify(state.elements));restore(state.history.pop())}function redo(){if(!state.future.length)return;state.history.push(JSON.stringify(state.elements));restore(state.future.pop())}
function addElement(type,data={}){snapshot();const base={id:uid(),type,name:type[0].toUpperCase()+type.slice(1),x:180,y:220,w:520,h:120,rotation:0,opacity:1,visible:true,locked:false,color:'#172033'};let el={...base,...data};if(['heading','subheading','body','quote','caption','thaana'].includes(type)){el.kind='text';el.text={heading:'Heading',subheading:'Subheading',body:'Body text',quote:'“Quote”',caption:'Caption',thaana:'ތާނަ ލިޔުން'}[type];el.font=type==='thaana'?'Noto Sans Thaana':'Arial';el.fontSize={heading:86,subheading:58,body:40,quote:64,caption:28,thaana:64}[type];el.weight=type==='heading'?800:700;el.h=150}else if(['rectangle','circle','line','arrow'].includes(type)){el.kind='shape';el.color='#15c89a';if(type==='rectangle'){el.w=360;el.h=180}else if(type==='circle'){el.w=220;el.h=220}else{el.w=360;el.h=60}}state.elements.push(el);state.selectedId=el.id;renderAll()}
function addImage(dataUrl){const img=new Image();img.onload=()=>{snapshot();state.elements.push({id:uid(),type:'image',kind:'image',name:'Image',x:140,y:160,w:800,h:600,rotation:0,opacity:1,visible:true,locked:false,src:dataUrl,naturalW:img.width,naturalH:img.height});state.selectedId=state.elements.at(-1).id;renderAll()};img.src=dataUrl}
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}
function rotatedPoint(p,e){const cx=e.x+e.w/2,cy=e.y+e.h/2,a=-e.rotation*Math.PI/180,dx=p.x-cx,dy=p.y-cy;return{x:cx+dx*Math.cos(a)-dy*Math.sin(a),y:cy+dx*Math.sin(a)+dy*Math.cos(a)}}
function hitElement(p){for(let i=state.elements.length-1;i>=0;i--){const e=state.elements[i];if(!e.visible)continue;const q=rotatedPoint(p,e);if(q.x>=e.x&&q.x<=e.x+e.w&&q.y>=e.y&&q.y<=e.y+e.h)return e}return null}
function handlePositions(e){const cx=e.x+e.w/2,cy=e.y+e.h/2;return{resize:{x:e.x+e.w,y:e.y+e.h},rotate:{x:cx,y:e.y-55}}}
function hitHandle(p,e){const q=rotatedPoint(p,e),h=handlePositions(e);if(Math.hypot(q.x-h.resize.x,q.y-h.resize.y)<28)return'resize';if(Math.hypot(q.x-h.rotate.x,q.y-h.rotate.y)<28)return'rotate';return null}
function drawElement(e){if(!e.visible)return;ctx.save();ctx.globalAlpha=e.opacity;ctx.translate(e.x+e.w/2,e.y+e.h/2);ctx.rotate(e.rotation*Math.PI/180);ctx.translate(-e.w/2,-e.h/2);if(e.kind==='text'){ctx.fillStyle=e.color;ctx.direction=/[ހ-޿]/.test(e.text)?'rtl':'ltr';ctx.textAlign='left';ctx.textBaseline='top';ctx.font=`${e.weight} ${e.fontSize}px "${e.font}",Arial,sans-serif`;const chars=[...e.text],lines=[];let line='';for(const ch of chars){const test=line+ch;if(ctx.measureText(test).width>e.w&&line){lines.push(line);line=ch}else line=test}if(line)lines.push(line);lines.forEach((l,i)=>ctx.fillText(l,0,i*e.fontSize*1.25))}else if(e.kind==='shape'){ctx.strokeStyle=ctx.fillStyle=e.color;ctx.lineWidth=12;if(e.type==='rectangle')ctx.fillRect(0,0,e.w,e.h);if(e.type==='circle'){ctx.beginPath();ctx.ellipse(e.w/2,e.h/2,e.w/2,e.h/2,0,0,Math.PI*2);ctx.fill()}if(e.type==='line'){ctx.beginPath();ctx.moveTo(0,e.h/2);ctx.lineTo(e.w,e.h/2);ctx.stroke()}if(e.type==='arrow'){ctx.beginPath();ctx.moveTo(0,e.h/2);ctx.lineTo(e.w-35,e.h/2);ctx.lineTo(e.w-75,10);ctx.moveTo(e.w-35,e.h/2);ctx.lineTo(e.w-75,e.h-10);ctx.stroke()}}else if(e.kind==='image'&&e.image){ctx.drawImage(e.image,0,0,e.w,e.h)}ctx.restore()}
function drawSelection(e){if(!e||!e.visible)return;ctx.save();ctx.translate(e.x+e.w/2,e.y+e.h/2);ctx.rotate(e.rotation*Math.PI/180);ctx.translate(-e.w/2,-e.h/2);ctx.strokeStyle='#15c89a';ctx.lineWidth=5;ctx.setLineDash([14,10]);ctx.strokeRect(0,0,e.w,e.h);ctx.setLineDash([]);ctx.fillStyle='#fff';ctx.strokeStyle='#15c89a';ctx.lineWidth=5;for(const [x,y] of [[0,0],[e.w,0],[0,e.h],[e.w,e.h]]){ctx.beginPath();ctx.arc(x,y,15,0,Math.PI*2);ctx.fill();ctx.stroke()}ctx.beginPath();ctx.moveTo(e.w/2,0);ctx.lineTo(e.w/2,-55);ctx.stroke();ctx.beginPath();ctx.arc(e.w/2,-55,15,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore()}
async function hydrateImages(){for(const e of state.elements.filter(x=>x.kind==='image'&&x.src&&!x.image)){await new Promise(r=>{const img=new Image();img.onload=()=>{e.image=img;r()};img.src=e.src})}}
async function render(){ctx.fillStyle=state.background;ctx.fillRect(0,0,canvas.width,canvas.height);await hydrateImages();state.elements.forEach(drawElement);drawSelection(selected())}
function renderLayers(){const box=$('#layerList');box.innerHTML='';[...state.elements].reverse().forEach(e=>{const row=document.createElement('button');row.className='layer-item'+(e.id===state.selectedId?' active':'');row.innerHTML=`<span>${e.name}<small>${e.type}</small></span><span>${e.locked?'🔒':e.visible?'◉':'○'}</span>`;row.onclick=()=>{state.selectedId=e.id;renderAll()};box.appendChild(row)})}
function renderInspector(){const e=selected();$('#emptyInspector').hidden=!!e;$('#inspector').hidden=!e;if(!e)return;$('.text-only').hidden=e.kind!=='text';for(const node of document.querySelectorAll('.text-only'))node.hidden=e.kind!=='text';$('#propName').value=e.name;$('#propX').value=Math.round(e.x);$('#propY').value=Math.round(e.y);$('#propW').value=Math.round(e.w);$('#propH').value=Math.round(e.h);$('#propR').value=Math.round(e.rotation);$('#propOpacity').value=e.opacity;$('#propColor').value=e.color||'#172033';if(e.kind==='text'){$('#propText').value=e.text;$('#propFont').value=e.font;$('#propFontSize').value=e.fontSize;$('#propWeight').value=e.weight}}
function renderAll(){render();renderLayers();renderInspector()}
canvas.addEventListener('pointerdown',e=>{const p=point(e),sel=selected();let mode=sel&&!sel.locked?hitHandle(p,sel):null;let target=sel;if(!mode){target=hitElement(p);state.selectedId=target?.id||null;if(target&&!target.locked)mode='move'}if(target&&mode){snapshot();interaction={mode,start:p,base:clone(target),id:target.id}}canvas.setPointerCapture(e.pointerId);renderAll()});
canvas.addEventListener('pointermove',e=>{if(!interaction)return;const p=point(e),el=state.elements.find(x=>x.id===interaction.id);if(!el)return;const dx=p.x-interaction.start.x,dy=p.y-interaction.start.y;if(interaction.mode==='move'){el.x=interaction.base.x+dx;el.y=interaction.base.y+dy}else if(interaction.mode==='resize'){el.w=Math.max(30,interaction.base.w+dx);el.h=Math.max(30,interaction.base.h+dy)}else if(interaction.mode==='rotate'){const cx=interaction.base.x+interaction.base.w/2,cy=interaction.base.y+interaction.base.h/2;el.rotation=Math.atan2(p.y-cy,p.x-cx)*180/Math.PI+90}renderAll()});
function end(){interaction=null}canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);canvas.addEventListener('dblclick',e=>{const el=hitElement(point(e));if(el?.kind==='text'){state.selectedId=el.id;renderAll();$('#propText').focus();$('#propText').select()}});
for(const b of document.querySelectorAll('[data-add]'))b.onclick=()=>addElement(b.dataset.add);$('#imageUpload').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>addImage(r.result);r.readAsDataURL(f)};
function changeProp(id,key,parse=v=>v){$('#'+id).addEventListener('input',()=>{const e=selected();if(!e)return;snapshot();e[key]=parse($('#'+id).value);renderAll()})}changeProp('propName','name');changeProp('propX','x',Number);changeProp('propY','y',Number);changeProp('propW','w',Number);changeProp('propH','h',Number);changeProp('propR','rotation',Number);changeProp('propOpacity','opacity',Number);changeProp('propColor','color');changeProp('propText','text');changeProp('propFont','font');changeProp('propFontSize','fontSize',Number);changeProp('propWeight','weight',Number);
$('#duplicate').onclick=()=>{const e=selected();if(!e)return;snapshot();const n={...clone(e),id:uid(),x:e.x+30,y:e.y+30};state.elements.push(n);state.selectedId=n.id;renderAll()};$('#deleteElement').onclick=()=>{if(!selected())return;snapshot();state.elements=state.elements.filter(e=>e.id!==state.selectedId);state.selectedId=null;renderAll()};$('#bringForward').onclick=()=>{const i=state.elements.findIndex(e=>e.id===state.selectedId);if(i<0||i===state.elements.length-1)return;snapshot();[state.elements[i],state.elements[i+1]]=[state.elements[i+1],state.elements[i]];renderAll()};$('#sendBackward').onclick=()=>{const i=state.elements.findIndex(e=>e.id===state.selectedId);if(i<=0)return;snapshot();[state.elements[i],state.elements[i-1]]=[state.elements[i-1],state.elements[i]];renderAll()};$('#toggleLock').onclick=()=>{const e=selected();if(!e)return;snapshot();e.locked=!e.locked;renderAll()};$('#toggleVisibility').onclick=()=>{const e=selected();if(!e)return;snapshot();e.visible=!e.visible;renderAll()};
$('#undo').onclick=undo;$('#redo').onclick=redo;window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}else if(e.key==='Delete'&&selected()){$('#deleteElement').click()}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='d'&&selected()){e.preventDefault();$('#duplicate').click()}});
function serializable(){return state.elements.map(({image,...e})=>e)}function download(blob,name){const a=document.createElement('a'),u=URL.createObjectURL(blob);a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}$('#saveProject').onclick=()=>download(new Blob([JSON.stringify({version:3,elements:serializable(),background:state.background},null,2)],{type:'application/json'}),'publisher-studio-project.json');$('#loadProject').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;const p=JSON.parse(await f.text());snapshot();state.elements=p.elements||[];state.background=p.background||'#fff';state.selectedId=null;renderAll()};$('#exportImage').onclick=()=>{const old=state.selectedId;state.selectedId=null;render().then(()=>canvas.toBlob(blob=>{download(blob,`publisher-studio.${$('#exportFormat').value==='jpeg'?'jpg':$('#exportFormat').value}`);state.selectedId=old;renderAll()},$('#exportFormat').value==='jpeg'?'image/jpeg':$('#exportFormat').value==='webp'?'image/webp':'image/png',.94))};
addElement('heading',{text:'Publisher Studio',x:160,y:160,w:760,color:'#172033'});state.history=[];renderAll();